namespace ComposableSettings.Generator.Helpers;

internal static class GeneratedSourceBuilder
{
    public static IndentedStringBuilder.IndentedStringBuilder Begin(string? namespaceName)
    {
        var sb = new IndentedStringBuilder.IndentedStringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        return sb;
    }
}
