using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ComposableSettings.Generator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ComposableSettings.Generator.SourceGenerators;

/// <summary>
/// Turns a <c>[SettingsConsumer(typeof(TSettings))] partial class</c> into a
/// settings consumer that stores NO settings state: emits the provider field,
/// a pass-through <c>Settings</c> property, and the <c>InitializeGeneratedSettings</c>
/// method (which the user calls from their own constructor) that wires the
/// <see cref="System.ComponentModel.INotifyPropertyChanged"/> relay.
/// </summary>
[Generator]
public class SettingsConsumerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new(
        "CSP022",
        "Settings consumer must be partial",
        "[SettingsConsumer] class '{0}' must be declared 'partial'",
        "ComposableSettings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingSettingsType = new(
        "CSP023",
        "Settings consumer requires a settings type",
        "[SettingsConsumer] on '{0}' requires a settings type argument",
        "ComposableSettings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AlreadyNotifies = new(
        "CSP024",
        "Settings consumer already implements INotifyPropertyChanged",
        "[SettingsConsumer] class '{0}' already implements INotifyPropertyChanged; the generator must own it in this version",
        "ComposableSettings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => GetCandidate(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(candidates.Collect(), Generate);
    }

    private static Candidate? GetCandidate(GeneratorSyntaxContext context)
    {
        var syntax = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(syntax) is not INamedTypeSymbol symbol)
            return null;

        var attribute = symbol.GetAttribute(GeneratorConstants.SettingsConsumerAttributeFullName);
        if (attribute is null)
            return null;

        var settingsType = attribute.ConstructorArguments.Length > 0
                           && attribute.ConstructorArguments[0].Value is INamedTypeSymbol t
            ? t
            : null;

        return new Candidate(syntax, symbol, settingsType);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<Candidate?> candidates)
    {
        foreach (var candidate in candidates)
        {
            if (candidate is not null)
                GenerateOne(context, candidate);
        }
    }

    private static void GenerateOne(SourceProductionContext context, Candidate candidate)
    {
        var symbol = candidate.Symbol;

        if (candidate.SettingsType is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingSettingsType, candidate.Syntax.Identifier.GetLocation(), symbol.Name));
            return;
        }

        if (!symbol.IsPartial())
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, candidate.Syntax.Identifier.GetLocation(), symbol.Name));
            return;
        }

        if (symbol.AllInterfaces.Any(i => i.ToDisplayString() == "System.ComponentModel.INotifyPropertyChanged"))
        {
            context.ReportDiagnostic(Diagnostic.Create(AlreadyNotifies, candidate.Syntax.Identifier.GetLocation(), symbol.Name));
            return;
        }

        context.AddSource(
            $"{symbol.ToDisplayString().Replace('.', '_')}.SettingsConsumer.g.cs",
            SourceText.From(BuildSource(symbol, candidate.SettingsType.ToGlobalTypeName()), Encoding.UTF8));
    }

    private static string BuildSource(INamedTypeSymbol type, string settingsType)
    {
        var ns = type.GetNamespaceName();
        var accessibility = type.GetAccessibilityText();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns.Length > 0)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"{accessibility} partial class {type.Name} : global::System.ComponentModel.INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine($"    private global::ComposableSettings.ISettingsProvider<{settingsType}> _settingsProvider = null!;");
        sb.AppendLine($"    private {settingsType}? _hookedSettings;");
        sb.AppendLine();
        sb.AppendLine($"    public {settingsType} Settings => _settingsProvider.Current;");
        sb.AppendLine();
        sb.AppendLine("    public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();
        sb.AppendLine($"    private void InitializeGeneratedSettings(global::ComposableSettings.ISettingsProvider<{settingsType}> provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _settingsProvider = provider;");
        sb.AppendLine("        RehookGeneratedSettings();");
        sb.AppendLine("        provider.Replaced += (_, _) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            RehookGeneratedSettings();");
        sb.AppendLine("            PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(nameof(Settings)));");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void RehookGeneratedSettings()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_hookedSettings is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _hookedSettings.PropertyChanged -= OnGeneratedSettingsChanged;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        _hookedSettings = _settingsProvider.Current;");
        sb.AppendLine("        _hookedSettings.PropertyChanged += OnGeneratedSettingsChanged;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void OnGeneratedSettingsChanged(object? sender, global::System.ComponentModel.PropertyChangedEventArgs e)");
        sb.AppendLine("        => PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(nameof(Settings)));");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class Candidate(ClassDeclarationSyntax syntax, INamedTypeSymbol symbol, INamedTypeSymbol? settingsType)
    {
        public ClassDeclarationSyntax Syntax { get; } = syntax;
        public INamedTypeSymbol Symbol { get; } = symbol;
        public INamedTypeSymbol? SettingsType { get; } = settingsType;
    }
}
