using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ComposableSettings.Generator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ComposableSettings.Generator.SourceGenerators;

[Generator]
public  class SettingsDIGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, ct) => GetClassInfo(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(classes.Collect(), GenerateDIExtension);
    }

    private static ClassInfo? GetClassInfo(GeneratorSyntaxContext context)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
            return null;

        var hasRoot = classSymbol.HasAttribute(GeneratorConstants.SettingsRootAttributeFullName);
        var hasComponent = classSymbol.HasAttribute(GeneratorConstants.SettingsComponentAttributeFullName);

        if (!hasRoot && !hasComponent)
            return null;

        return new ClassInfo(classSymbol.ToGlobalTypeName());
    }

    private static void GenerateDIExtension(
        SourceProductionContext context,
        ImmutableArray<ClassInfo?> classes)
    {
        var classList = classes
            .Where(c => c is not null)
            .Select(c => c!)
            .GroupBy(c => c.ClassName)
            .Select(g => g.First())
            .ToList();

        if (classList.Count == 0) return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        source.AppendLine();
        source.AppendLine("namespace ComposableSettings.Generated;");
        source.AppendLine();
        source.AppendLine("public static partial class GeneratedSettingsServiceCollectionExtensions");
        source.AppendLine("{");
        source.AppendLine(
            "    public static IServiceCollection AddGeneratedSettingsComponents(this IServiceCollection services)");
        source.AppendLine("    {");

        foreach (var cls in classList) source.AppendLine($"        services.AddTransient<{cls.ClassName}>();");

        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(
            "GeneratedSettingsServiceCollectionExtensions.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private  class ClassInfo(string className)
    {
        public string ClassName { get; } = className;
    }
}