using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ComposableSettings.Generator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ComposableSettings.Generator.SourceGenerators;

/// <summary>
/// Turns a <c>[SettingsModel] partial class</c> into an observable settings model:
/// emits <see cref="System.ComponentModel.INotifyPropertyChanged"/> plus a public,
/// change-raising property for every instance field named <c>_camelCase</c>.
/// Defaults come from the field initializers the user already wrote.
/// </summary>
[Generator]
public class SettingsModelGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new(
        "CSP020",
        "Settings model must be partial",
        "[SettingsModel] class '{0}' must be declared 'partial' for INotifyPropertyChanged generation",
        "ComposableSettings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AlreadyNotifies = new(
        "CSP021",
        "Settings model already implements INotifyPropertyChanged",
        "[SettingsModel] class '{0}' already implements INotifyPropertyChanged; remove the base/interface and let the generator provide it",
        "ComposableSettings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => GetCandidate(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(candidates.Collect(), Generate);
    }

    private static Candidate? GetCandidate(GeneratorSyntaxContext context)
    {
        var syntax = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(syntax) is not INamedTypeSymbol symbol)
            return null;
        return symbol.HasAttribute(GeneratorConstants.SettingsModelAttributeFullName)
            ? new Candidate(syntax, symbol)
            : null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<Candidate?> candidates)
    {
        foreach (var candidate in candidates)
        {
            if (candidate is not null)
                GenerateOne(context, candidate);
        }
    }

    private static void GenerateOne(SourceProductionContext context, Candidate candidate)
    {
        var symbol = candidate.Symbol;

        if (!symbol.IsPartial())
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, candidate.Syntax.Identifier.GetLocation(), symbol.Name));
            return;
        }

        if (symbol.AllInterfaces.Any(i => i.ToDisplayString() == "System.ComponentModel.INotifyPropertyChanged"))
        {
            context.ReportDiagnostic(Diagnostic.Create(AlreadyNotifies, candidate.Syntax.Identifier.GetLocation(), symbol.Name));
            return;
        }

        var fields = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => !f.IsImplicitlyDeclared && !f.IsStatic && !f.IsConst && !f.IsReadOnly
                        && f.AssociatedSymbol is null
                        && f.Name.StartsWith("_", StringComparison.Ordinal)
                        && f.Name.TrimStart('_').Length > 0)
            .Select(f => new FieldModel(f.Name, ToPropertyName(f.Name), f.Type.ToGlobalTypeName()))
            .Where(fm => !symbol.GetMembers(fm.PropertyName).OfType<IPropertySymbol>().Any())
            .ToList();

        if (fields.Count == 0)
            return;

        context.AddSource(
            $"{symbol.ToDisplayString().Replace('.', '_')}.SettingsModel.g.cs",
            SourceText.From(BuildSource(symbol, fields), Encoding.UTF8));
    }

    private static string ToPropertyName(string fieldName)
    {
        var trimmed = fieldName.TrimStart('_');
        return char.ToUpperInvariant(trimmed[0]) + trimmed.Substring(1);
    }

    private static string BuildSource(INamedTypeSymbol type, IReadOnlyList<FieldModel> fields)
    {
        var ns = type.GetNamespaceName();
        var accessibility = type.GetAccessibilityText();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns.Length > 0)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"{accessibility} partial class {type.Name} : global::System.ComponentModel.INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine("    public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();

        foreach (var field in fields)
        {
            sb.AppendLine($"    public {field.TypeName} {field.PropertyName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => {field.FieldName};");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (!global::System.Collections.Generic.EqualityComparer<{field.TypeName}>.Default.Equals({field.FieldName}, value))");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.FieldName} = value;");
            sb.AppendLine($"                PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(nameof({field.PropertyName})));");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class Candidate(ClassDeclarationSyntax syntax, INamedTypeSymbol symbol)
    {
        public ClassDeclarationSyntax Syntax { get; } = syntax;
        public INamedTypeSymbol Symbol { get; } = symbol;
    }

    private sealed class FieldModel(string fieldName, string propertyName, string typeName)
    {
        public string FieldName { get; } = fieldName;
        public string PropertyName { get; } = propertyName;
        public string TypeName { get; } = typeName;
    }
}
